version: "3"
services:
  apache-php-cliente1:
    build:
      context: ./multicuenta/cliente1
      dockerfile: Dockerfile
    ports:
      - "82:80"
    volumes:
      - "./multicuenta/cliente1/conf/hstienda.tk.conf:/etc/apache2/sites-available/000-default.conf"
      - "./multicuenta/cliente1/public_html:/var/www/html"
    depends_on:
      - mysql-cliente1
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cliente1_db"
      MYSQL_USER: "cliente1_user"
      MYSQL_PASSWORD: "cliente1_password"

  mysql-cliente1:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cliente1_db"
      MYSQL_USER: "cliente1_user"
      MYSQL_PASSWORD: "cliente1_password"
