version: "3"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql-cliente1
    environment:
      PMA_HOSTS: mysql-cliente1, mysql-cliente2
      PMA_PORTS: 3306, 3306
      PMA_ARBITRARY: 1

  apache-php-cliente1:
    build:
      context: ./multicuenta/cliente1
      dockerfile: Dockerfile
    ports:
      - "82:80"
    volumes:
      - "./multicuenta/cliente1/conf/hstienda.tk.conf:/etc/apache2/sites-available/000-default.conf"
      - "./multicuenta/cliente1/public_html:/var/www/html"
    depends_on:
      - mysql-cliente1
    environment:
      DOMINIO: "hstienda.tk"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cliente1_db"
      MYSQL_USER: "cliente1_user"
      MYSQL_PASSWORD: "cliente1_password"

  mysql-cliente1:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cliente1_db"
      MYSQL_USER: "cliente1_user"
      MYSQL_PASSWORD: "cliente1_password"

  apache-php-cliente2:
    build:
      context: ./multicuenta/cliente2
      dockerfile: Dockerfile
    ports:
      - "83:80"
    volumes:
      - "./multicuenta/cliente2/conf/hausegamming.tk.conf:/etc/apache2/sites-available/000-default.conf"
      - "./multicuenta/cliente2/public_html:/var/www/html"
    depends_on:
      - mysql-cliente2
    environment:
      DOMINIO: "hausegamming.tk"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cliente2_db"
      MYSQL_USER: "cliente2_user"
      MYSQL_PASSWORD: "cliente2_password"

  mysql-cliente2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cliente2_db"
      MYSQL_USER: "cliente2_user"
      MYSQL_PASSWORD: "cliente2_password"
