version: "3"
services:
  apache-php-cliente2:
    build:
      context: ./multicuenta/cliente2
      dockerfile: Dockerfile
    ports:
      - "83:80"
    volumes:
      - "./multicuenta/cliente2/conf/hausegamming.tk.conf:/etc/apache2/sites-available/000-default.conf"
      - "./multicuenta/cliente2/public_html:/var/www/html"
    depends_on:
      - mysql-cliente2
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cliente2_db"
      MYSQL_USER: "cliente2_user"
      MYSQL_PASSWORD: "cliente2_password"

  mysql-cliente2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cliente2_db"
      MYSQL_USER: "cliente2_user"
      MYSQL_PASSWORD: "cliente2_password"
