version: "3"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS: mysql-cliente1, mysql-cliente2
      PMA_PORTS: 3306, 3306
      PMA_ARBITRARY: 1
